/** @type {import('tailwindcss').Config} */
export default {
    content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                primary: "#16a34a",
                secondary: "#dcfce7",
                background: "#fff",
                foreground: "oklch(0.145 0 0)",
                card: "#fff",
                'card-foreground': "oklch(0.145 0 0)",
                'font-size': "16px",
                popover: "oklch(1 0 0)",
                'popover-foreground': "oklch(0.145 0 0)",
                'primary-foreground': "#ffffff",
                'secondary-foreground': "#166534",
                muted: "#f3f4f6",
                'muted-foreground': '#6b7280',
                accent: "#bbf7d0",
                'accent-foreground': "#166534",
                destructive: "#d4183d",
                'destructive-foreground': "#ffffff",
                border: "rgba(0, 0, 0, 0.1)",
                input: "transparent",
                inputbackground: '#f9fafb',
                'switch-background': "#cbced4",
                'font-weight-medium': "500",
                'font-weight-normal': "400",
                ring: "#16a34a",
                'chart-1': "oklch(0.646 0.222 41.116)",
                'chart-2': "oklch(0.6 0.118 184.704)",
                'chart-3': "oklch(0.398 0.07 227.392)",
                'chart-4': "oklch(0.828 0.189 84.429)",
                'chart-5': "oklch(0.769 0.188 70.08)",
                radius: "0.625rem",
                sidebar: "oklch(0.985 0 0)",
                'sidebar-foreground': "oklch(0.145 0 0)",
                'sidebar-primary': "#16a34a",
                'sidebar-primary-foreground': "#ffffff",
                'sidebar-accent': "oklch(0.97 0 0)",
                'sidebar-accent-foreground': "oklch(0.205 0 0)",
                'sidebar-border': "oklch(0.922 0 0)",
                'sidebar-ring': "oklch(0.708 0 0)",

            },
        },
    },
    plugins: [],
};
